### ISSUE TITLE
Lacks a signature

### ISSUE THREAD

**Issue by domenkozar** [peti/hydra-tutorial#3]
I've followed the tutorial to setup a Hydra cluster. Thanks again!

There's a peculiar error going on that I don't understand how exactly it should be addressed.

`Aborted: imported archive of ‘/nix/store/nj34rl1sn86b50l940qgnmrcr6wbyal2-snabb-manual’ lacks a signature` at https://hydra.snabb.co/build/16

Here's my Hydra master file: https://github.com/snabblab/snabblab-nixos/blob/master/modules/hydra-master.nix
And slave: https://github.com/snabblab/snabblab-nixos/blob/master/modules/hydra-slave.nix

I noticed Mayflower also generates another key, not sure if this is relevant: https://github.com/mayflower/mf-nixops/blob/master/component/hydra.nix#L65

cc @peti

**Comment by domenkozar** [comment]
Maybe I need to apply https://github.com/NixOS/hydra/commit/b00bdefa98bd86de7e66e6d8d33f1bc5da81330f as I'm using https://github.com/NixOS/hydra/commit/993647d1e3b43f1f9b7dc2ebce889b475d156bb9 commit for deploying Hydra?

**Comment by domenkozar** [comment]
I think I have figured out the issue, but I don't know what's best to do about it yet.

If you build something manually with `nix-build` on build slaves, Hydra will reuse those drvs if they can be imported for the running job. But since those drvs weren't built using Hydra signing key, Hydra would barf on missing signature.

**Comment by peti** [comment]
I don't think that binaries are signed in any way. Hydra adds that signature to generated narinfo files, but those are created on the fly and not stored anywhere. Basically, everything in your store is implicitly trusted and not signed.

Personally, I've never see the error you've described, but I _guess_ that what is missing is a shared signing key that Hydra and its slaves can use for transferring closures `nix-copy-closue`-style, i.e. the `/etc/nix/signing-key.*` files you've mentioned earlier. See https://github.com/NixOS/nix/blob/master/doc/signing.txt on how to generate them. Maybe that helps remedy this issue?

**Comment by domenkozar** [comment]
I'll try now with Nix signing keys.

**Comment by domenkozar** [comment]
According to Eelco it shouldn't need keys (see also https://github.com/NixOS/nix/commit/525c78a2c3a1da5b673d11478d3b1693a7579508). I'm running now Hydra from master, let's see if this still happens.

**Comment by peti** [comment]
Did you have that error again? Or is it gone?

**Comment by domenkozar** [comment]
Using newer `release-16.03` and newer `hydra` commit the issue is gone.

**Comment by ElvishJerricco** [comment]
On NixOS 17.09 on both the master and the slave, using the version of `hydra` that comes with it, and I'm getting this error.
